accumulation_steps: null
amp_opt_level: O1
batch_size: 1
cache_mode: part
cfg: configs/vt_unet_tiny.yaml
devices: '0'
epochs: 300
eval: false
exp_name: logs_base
fold: 0
lr: 0.0001
num_classes: 2
resume: 0
seed: 1234
start_epoch: 0
tag: null
throughput: false
use_checkpoint: false
val: 1
weight_decay: 0
workers: 2
zip: false
